# Generated by Django 5.1.1 on 2025-10-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_profile_old_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
