# Generated by Django 5.1.1 on 2025-10-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='old_cart',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
