# Generated by Django 5.1.1 on 2025-10-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_alter_profile_old_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='old_cart',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
