# Generated by Django 5.1.1 on 2025-10-12 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_alter_profile_old_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='old_cart',
        ),
    ]
