# Generated by Django 5.1.1 on 2025-10-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_remove_profile_old_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_cart',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
